name: 'My First GitHub Actions Workflow' # 워크플로우 이름
on: push #코드가 github으로 push 됐을 때 작동 == 트리거이벤트

env:
  WORKFLOW_LEVEL: 'This values comes from the workflow level' #jobs에서도 가능, 각각의 steps에서도 환경변수 설정 가능

jobs: 
  first-job: 
    name: 'First Job' #하는 일 각각의 빌드 서버가 할당된다.
    runs-on: ubuntu-latest #빌드 서버의 운영 체제, 여러 개 사용 가능

    steps:
    - name: 'Set environment variable 1' # 네임 하나가 각각의 스텝
      shell: bash
      run: |
        echo $GITHUB_ENV
        echo "STEP_1 = 'This value comes from the step 1'" >> $GITHUB_ENV
    - name: 'Set environment variable 2'
      shell: pwsh

      run: |
        echo "STEP_2='Lorem Ipsum from Step 2'" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf-8 -Append
    - name: 'Get environment variables'
      shell: bash
      run: |
        echo "WORKFLOW: ${{ env.WORKFLOW_LEVEL }}"
        echo "STEP 1: ${{ env.STEP_1 }}"
        echo "STEP 2: ${{ env.STEP_2 }}"