name: 'My First GitHub Actions Workflow' # 워크플로우 이름
on: push #코드가 github으로 push 됐을 때 작동 == 트리거이벤트

env:
  WORKFLOW_LEVEL: 'This values comes from the workflow level' #jobs에서도 가능, 각각의 steps에서도 환경변수 설정 가능

jobs: 
  first-job: 
    if: github.event_name == 'pull_request'
    name: 'First Job' #하는 일 각각의 빌드 서버가 할당된다.

    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest','macos-latest']
        nodejs: ['14.x', '16.x']
    runs-on: ${{ matrix.os }} #빌드 서버의 운영 체제, 여러 개 사용 가능

    steps:
    - name: 'Setup node.js version' # 네임 하나가 각각의 스텝
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.nodejs }}

    - name: 'Run only on Windows'
      if: matrix.os == 'windows-latest'
      shell: bash
      run: |
        echo "Windows Only"

    - name: 'Run not on Windows'
      if: matrix.os != 'windows-latest'
      shell: bash
      run: |
        echo "Not Windows"
    
    - name: 'Check node.js version on ${{ matrix.os }} '
      shell: bash
      run: |
        echo $(node --version)

