name: 'My First GitHub Actions Workflow' # 워크플로우 이름
on: push #코드가 github으로 push 됐을 때 작동 == 트리거이벤트

env:
  WROKFLOW_LEVEL: 'This values comes from the workflow level' #jobs에서도 가능, 각각의 steps에서도 환경변수 설정 가능

jobs: 
  first-job: 
    name: 'First Job' #하는 일 각각의 빌드 서버가 할당된다.
    runs-on: ubuntu-latest #빌드 서버의 운영 체제, 여러 개 사용 가능
    env:
      JOB_LEVEL_1: 'This values comes from the job level' #jobs에서도 가능, 각각의 steps에서도 환경변수 설정 가능

    steps:
    - name: 'Say Hello World on step 1' # 네임 하나가 각각의 스텝
      shell: bash
      env:
        STEP_LEVEL_1: 'This values comes from the step 1' #jobs에서도 가능, 각각의 steps에서도 환경변수 설정 가능

      run: |
        echo "Hello World from Step 1"
        echo "Workflow Level: $WORKFLOW_LEVEL"
        echo "Job Level: $JOB_LEVEL_1"
        echo "Job Level: $JOB_LEVEL_2"
        echo "Step 1: $STEP_LEVEL_1"
        echo "Step 2: $STEP_LEVEL_2"
    - name: 'Say Lorem Ipsum on step 2'
      shell: pwsh
      env:
        STEP_LEVEL_2: 'This values comes from the step 2' #jobs에서도 가능, 각각의 steps에서도 환경변수 설정 가능

      run: |
        echo "Lorem Ipsum from Step 2"
        echo "Workflow Level: $env:WORKFLOW_LEVEL"
        echo "Job Level: $env:JOB_LEVEL_1"
        echo "Job Level: $env:JOB_LEVEL_2"
        echo "Step 1: $env:STEP_LEVEL_1"
        echo "Step 2: $env:STEP_LEVEL_2"
  second-job: 
    name: 'Second Job' #하는 일 각각의 빌드 서버가 할당된다.
    runs-on: ubuntu-latest #빌드 서버의 운영 체제, 여러 개 사용 가능
    env:
      JOB_LEVEL_2: 'This values comes from the job level' #jobs에서도 가능, 각각의 steps에서도 환경변수 설정 가능

    steps:
    - name: 'Say Hello World on step 1' # 네임 하나가 각각의 스텝
      shell: bash
      env:
        STEP_LEVEL_1: 'This values comes from the step 1' #jobs에서도 가능, 각각의 steps에서도 환경변수 설정 가능

      run: |
        echo "Hello World from Step 1"
        echo "Workflow Level: $WORKFLOW_LEVEL"
        echo "Job Level: $JOB_LEVEL_1"
        echo "Job Level: $JOB_LEVEL_2"
        echo "Step 1: $STEP_LEVEL_1"
        echo "Step 2: $STEP_LEVEL_2"
    - name: 'Say Lorem Ipsum on step 2'
      shell: pwsh
      env:
        STEP_LEVEL_2: 'This values comes from the step 2' #jobs에서도 가능, 각각의 steps에서도 환경변수 설정 가능

      run: |
        echo "Lorem Ipsum from Step 2"
        echo "Workflow Level: $env:WORKFLOW_LEVEL"
        echo "Job Level: $env:JOB_LEVEL_1"
        echo "Job Level: $env:JOB_LEVEL_2"
        echo "Step 1: $env:STEP_LEVEL_1"
        echo "Step 2: $env:STEP_LEVEL_2"

  