name: 'My First GitHub Actions Workflow' # 워크플로우 이름
on: push #코드가 github으로 push 됐을 때 작동 == 트리거이벤트

env:
  WORKFLOW_LEVEL: 'This values comes from the workflow level' #jobs에서도 가능, 각각의 steps에서도 환경변수 설정 가능

jobs: 
  first-job: 
    name: 'First Job' #하는 일 각각의 빌드 서버가 할당된다.

    strategy:
      matrix:
        os: ['ubuntu-latest', 'windows-latest','macos-latest']
    runs-on: ${{ matrix.os }} #빌드 서버의 운영 체제, 여러 개 사용 가능

    steps:
    - name: 'Say Hello on ${{ matrix.os }}' # 네임 하나가 각각의 스텝
      shell: bash
      run: | #마스킹을 통해 민감한 정보를 가릴 수 있다. github settings에서 secret을 정할수잇음
        echo "Hello from ${{ matrix.os }}"
