name: 'My First GitHub Actions Workflow' # 워크플로우 이름
on: push #코드가 github으로 push 됐을 때 작동 == 트리거이벤트

env:
  WORKFLOW_LEVEL: 'This values comes from the workflow level' #jobs에서도 가능, 각각의 steps에서도 환경변수 설정 가능

jobs: 
  first-job: 
    name: 'First Job' #하는 일 각각의 빌드 서버가 할당된다.
    runs-on: ubuntu-latest #빌드 서버의 운영 체제, 여러 개 사용 가능

    steps:
    - name: 'Set output value 1' # 네임 하나가 각각의 스텝
      id: step1
      shell: bash
      run: | #마스킹을 통해 민감한 정보를 가릴 수 있다. github settings에서 secret을 정할수잇음
        STEP_1='This value comes from the step 1'
        echo "::add-mask::$STEP_1"
        echo "::set-output name=value1::$STEP_1"

    - name: 'Set output value 2'
      id: step2
      shell: pwsh

      run: |
        $STEP_2='This value comes from the step 2'
        echo "::set-output name=value2::$STEP_2"

    - name: 'Get output values'
      shell: pwsh
      run: |
        echo "STEP 1: ${{ steps.step1.outputs.value1 }}"
        echo "STEP 2: ${{ steps.step2.outputs.value2 }}"
        echo "SECRET 1: ${{ secrets.SECRET_1 }}"